[package]
name = "enval"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
description = "Environment variable abstraction layer"

[dependencies]
thiserror = { workspace = true }
num_threads = { workspace = true, optional = true }

[features]
default = []
# Enable integration with the standard library.
std = ["dep:num_threads"]
