[package]
name = "pathal"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
description = "Path abstraction layer"

[dependencies]
thiserror = { workspace = true }

[features]
default = []
# Enable integration with the standard library.
std = []
